### ISSUE TITLE
URI Parsing Issue

### ISSUE THREAD

**Issue by pranshuchittora** [hectorm/otpauth#17]
Hi, 
I am trying to parse this URI -> otpauth://totp/Hello?secret=gyevisscogih3lbeaqfb3atrgcdaqcpo5ns3cs637uj4mo735q4tmwup&algorithm=SHA256&digits=6&period=30&lock=false
Getting error while parsing.

```js
if (!Array.isArray(uriGroups)) {
        throw new URIError('Invalid URI format');
      } // Extract URI groups.
```
Generate from https://freeotp.github.io/qrcode.html
Google Authenticator App is able to parse this

**Comment by hectorm** [comment]
It seems that the `lock` parameter is causing the problem. That parameter is not specified in the [key URI format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format), FreeOTP has recently added it (freeotp/freeotp.github.io#16).

I've updated OTPAuth to ignore unknown parameters instead of throwing an exception.
