### ISSUE TITLE
How to validate with google authenticator?

### ISSUE THREAD

**Issue by OrShalmayev** [hectorm/otpauth#228]
Hi, I'm generating QR with the library ```OtpAuth.toString();``` but I didn't understand how can I validate google auth digits?

**Comment by hectorm** [comment]
I suggest you start by learning how TOTP ([RFC 6238](https://datatracker.ietf.org/doc/rfc6238/)) works (for example, see [this post](https://hackernoon.com/implementing-2fa-how-time-based-one-time-password-actually-works-with-python-examples-cm1m3ywt) or [this other post](https://rublon.com/blog/what-is-totp/)).

Basically, both Google Authenticator and your application must share the same secret so that the generated codes are the same.
