### ISSUE TITLE
Use SubtleCrypto in browser

### ISSUE THREAD

**Issue by socketpair** [hectorm/otpauth#296]
Use https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest when work in browser

Unfortunately it is asynchronous. Anyway, I think it is better than external crypto dependency.

**Comment by hectorm** [comment]
If I were writing OTPAuth today, I would probably use the Web Crypto API for this part, but as you point out, the digest method can only be used asynchronously and also supports fewer algorithms than jsSHA (although SHA1 is what is almost always used in TOTP), so making OTPAuth use it would be a breaking change, and since jsSHA currently works fine, I have no strong reason to replace it.
