### ISSUE TITLE
Better approach in `uintToBuf` implementation 

### ISSUE THREAD

**Issue by Harsh-br0** [hectorm/otpauth#385]
I was skimming through this repo to get idea for using `Web Crypto` API , and i saw buffer conversion for `counter` in both `HOTP` and `TOTP` generations...

I think here it can have bit shifting to right.

https://github.com/hectorm/otpauth/blob/e8ef2abbe73789a4184348e9c0dc14d81125b1c0/src/utils/encoding/uint.js#L13-L15

Like this

```js
arr[i] = acc & 255; 
acc >>= 8;
```

I was curious to know a rationale for having this division approach so i made this issue.

**Comment by hectorm** [comment]
I've tried your approach and some test cases fail because it doesn't seem to handle numbers larger than 32 bit, which I calculated using the default TOTP options would be a problem in `4011-07-14T01:04:00Z`, and I can't imagine the nightmare of fixing a legacy system still using this library at that time. However, I haven't looked at this part of the code for a while, so I'm open to any optimisations you can suggest.

**Comment by hectorm** [comment]
The BigInt implementation you provide works correctly, but I prefer not to use BigInt if we already have an efficient implementation that does not require it. Anyway, I really appreciate your effort to analyze the code and provide constructive feedback.
