### ISSUE TITLE
TypeError: Unknown hash function when deployed on Cloudflare

### ISSUE THREAD

**Issue by DDuran19** [hectorm/otpauth#552]
Hi! It works just fine locally but when deployed in cloudflare, whether it's SHA-1 or SHA-256. it ends up saying unknown hash function

here's my code

```ts

import { getConfigFor } from '$lib/server/common/config';
import { TOTP, Secret } from 'otpauth';
import { injectable } from 'tsyringe';

@injectable()
export class OTPAuthService {
	registerNewMFA() {
		const secret = new Secret();
		const otpAuth = new TOTP({
			issuer: getConfigFor('TOTP').issuer,
			label: getConfigFor('TOTP').label,
			algorithm: 'SHA-256',
			digits: 6,
			secret
		});

		const uri = otpAuth.toString();

		return {
			secret, // Gonna be saved in the database
			uri // Gonna be displayed to the user via QR code
		};
	}

	verifyCode(secret: Secret | string, token: string) {
		const otpAuth = new TOTP({
			issuer: getConfigFor('TOTP').issuer,
			label: getConfigFor('TOTP').label,
			algorithm: 'SHA-256',
			digits: 6,
			secret
		});

		const delta = otpAuth.validate({ token, window: 1 });
		if (delta === null) {
			return false;
		}

		return true;
	}
}

```

is the library inherintly not available for CF or I just did something wrong? Please help thank you :)

**Comment by hectorm** [comment]
Hi, the correct values for the `algorithm` property are: `SHA1`, `SHA224`, `SHA256`, `SHA384`, `SHA512`, `SHA3-224`, `SHA3-256`, `SHA3-384` and `SHA3-512`. 

It may work locally for you because when running on Node.js it uses the `crypto` module and supports various aliases for algorithm names, but on all other platforms it uses the `@noble/hashes` library.

Perhaps I should update the type definitions to restrict the possible values of this property to avoid confusion.

**Comment by DDuran19** [comment]
Thank you! I used the algorithm values, but it still fails.. Am I doing something wrong? or is the package not supposed to work on serverless environments like cloudflare?

**Comment by DDuran19** [comment]
Hey my man, I got it to work, cheers! You're the best!
