### ISSUE TITLE
Undefined is not an object ( evalutating 'InternalUtils.globalThis.process')

### ISSUE THREAD

**Issue by veris-NikhilSrivastava** [hectorm/otpauth#6]
This library is crashing in react-native iOS version 11.
Please help me out with this.

Environment:
react: 16.8.6
react-native: 0.60.4
Platform : iOS 11

**Comment by hectorm** [comment]
I've no experience with React Native, but I followed the [getting started guide](https://facebook.github.io/react-native/docs/getting-started), imported OTPAuth into the project and it worked for me.

I've only been able to try it on Android, since I don't have any iOS device.

Could you provide an example project that produces the exception?

**Comment by perry-mitchell** [comment]
This is also happening for me, and it breaks on iOS 11 but not on iOS 13, for some reason:

![image](https://user-images.githubusercontent.com/3869469/71786736-aa6ef180-3017-11ea-9347-dfad213b39fe.png)

> I don't have any iOS device

I guess you're not on a mac then? Otherwise you could try creating an iOS simulator..

> Could you provide an example project that produces the exception?

https://github.com/buttercup/buttercup-mobile - A bit overkill, but it fails like in my screenshot in master.. It seems like the globalThis ponyfill you're using is not compatible with react-native on iOS 11 🤔.

**Comment by perry-mitchell** [comment]
Would there be a fail-safe way of handling this, rather than trying to figure out what RN is doing? Perhaps some override so we can skip this check, or a try-catch so it defaults to X value if an exception is caught? Happy to make a PR for any of these options of course 🙂

**Comment by hectorm** [comment]
The code of this polyfill [was originally written by Mathias Bynens](https://mathiasbynens.be/notes/globalthis), until now I had not found a platform where it did not work. Since it works on iOS 13 and not on iOS 11, I will try to reproduce the problem on an older version of WebKit on a macOS VM.

**Comment by perry-mitchell** [comment]
@hectorm Thank you! I can also debug this a bit further.. perhaps there’s a nice way to catch what’s going on for iOS 11. I’ll submit a PR if I find something.

**Comment by perry-mitchell** [comment]
@hectorm It seems that the `__magicalGlobalThis__` trick doesn't work at all in React-Native on iOS 11 - it's simply undefined. Would you be open to adding a fallback to this method to simply try and fetch the global object in a naive manner?

Something like this perhaps:

```javascript
if (typeof global === "object") {
	_globalThis = global;
} else if (typeof window === "object") {
	_globalThis = window;
}
```

Might even be worth considering throwing an error in this method if the value is still `undefined` - would make tracing the issue a bit easier perhaps :)

**Comment by perry-mitchell** [comment]
It seems that `this` here is always `undefined`:

https://github.com/hectorm/otpauth/blob/master/src/utils.js#L248

It raises the question: What is more ideal? Failing hard or using a _naive_ globalThis which would simply point to the global object in these obscure cases. I'll make a PR for this so you can see what I'm suggesting :)

**Comment by perry-mitchell** [comment]
@hectorm Thanks again for the help! Now have your library working really well in our mobile app:

![image](https://user-images.githubusercontent.com/3869469/71920011-9ac5e900-318e-11ea-856b-5775d78d6c94.png)

https://buttercup.pw uses your library on mobile and within the browser extension so far - The CLI and desktop apps will be using it soon.

**Comment by hectorm** [comment]
I'm glad my library is serving you well :smile:
