### ISSUE TITLE
What is the difference with @yeojz/otplib

### ISSUE THREAD

**Issue by YouthLin** [hectorm/otpauth#9]
Hi, this repo is realy a wonderful repo!
And I have find a similar tool before: https://github.com/yeojz/otplib
Counld you tell something different between them?

**Comment by hectorm** [comment]
Personally I can't talk about otplib because I haven't used it, however I would say that my library is a simpler and more lightweight implementation (8.73 KB vs 17.8 KB) of the HOTP and TOTP RFCs.

I invite you to check the documentation of both projects and choose the one that best suits your needs.
